#!/usr/bin/env bash
# ==============================================================================
# sdrive-tail-client.sh - Real-time Client Traffic Monitor
# ==============================================================================
# Tails the Caddy reverse proxy logs and filters specifically for traffic
# generated by the custom Android client app. Useful for debugging background
# uploads, API connection issues, and ensuring Tailscale traffic is routing.
#
# Usage:
#   ./scripts/sdrive-tail-client.sh
# ==============================================================================
set -euo pipefail

echo "======================================================================"
echo " sdrive - Tailing Client Traffic via Caddy"
echo " Press Ctrl+C to stop."
echo "======================================================================"

# The custom app typically uses a specific User-Agent containing 'ente' or 'okhttp'
# Adjust the grep filter if the teammate changes the User-Agent in the fork.
docker logs -f sdrive-stack-caddy-1 2>&1 | grep -iE 'ente|okhttp' | \
while read -r line; do
    # Basic highlighting of HTTP status codes for readability
    if echo "$line" | grep -q '"status":2'; then
        echo -e "\033[0;32m$line\033[0m" # Green for 2xx
    elif echo "$line" | grep -q '"status":4'; then
        echo -e "\033[0;33m$line\033[0m" # Yellow for 4xx
    elif echo "$line" | grep -q '"status":5'; then
        echo -e "\033[0;31m$line\033[0m" # Red for 5xx
    else
        echo "$line"
    fi
done
